version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    container_name: exfin_postgres
    environment:
      POSTGRES_DB: exfin_rest
      POSTGRES_USER: exfin_user
      POSTGRES_PASSWORD: exfin_password123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U exfin_user -d exfin_rest"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Hasura GraphQL Engine
  hasura:
    image: hasura/graphql-engine:v2.33.4
    container_name: exfin_hasura
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://exfin_user:exfin_password123@postgres:5432/exfin_rest
      HASURA_GRAPHQL_ADMIN_SECRET: exfin_admin_secret_2024
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLE_TELEMETRY: "false"
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/healthz"]
      interval: 10s
      timeout: 5s
      retries: 5

  # MinIO File Storage
  minio:
    image: minio/minio:latest
    container_name: exfin_minio
    environment:
      MINIO_ROOT_USER: exfin_minio_access
      MINIO_ROOT_PASSWORD: exfin_minio_secret_2024
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Auth Service (Go)
  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    container_name: exfin_auth
    environment:
      PORT: 8081
      JWT_SECRET: exfin_jwt_secret_2024
      DATABASE_URL: postgres://exfin_user:exfin_password123@postgres:5432/exfin_rest
      HASURA_URL: http://hasura:8080
    ports:
      - "8081:8081"
    depends_on:
      postgres:
        condition: service_healthy
      hasura:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  # API Gateway
  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    container_name: exfin_api_gateway
    environment:
      PORT: 3000
      AUTH_SERVICE_URL: http://auth-service:8081
      HASURA_URL: http://hasura:8080
      MINIO_URL: http://minio:9000
      JWT_SECRET: exfin_jwt_secret_2024
      HASURA_ADMIN_SECRET: exfin_admin_secret_2024
      MINIO_ACCESS_KEY: exfin_minio_access
      MINIO_SECRET_KEY: exfin_minio_secret_2024
      MINIO_BUCKET_NAME: exfin-rest-files
      NODE_ENV: production
      RATE_LIMIT_WINDOW_MS: 900000
      RATE_LIMIT_MAX_REQUESTS: 100
      CORS_ORIGINS: http://localhost:3000,http://localhost:8080,http://localhost:9001
    ports:
      - "3000:3000"
    depends_on:
      auth-service:
        condition: service_healthy
      hasura:
        condition: service_healthy
      minio:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  minio_data: 